### ISSUE TITLE
App crashes when Locale has no country code

### ISSUE THREAD

**Issue by ElZombieIsra** [localizely/flutter-intl-vscode#10]
Hi

My app is crashing when i try to change the locale using `S.load(locale)`.

I've already traced the problem to the generated code in the file **l10n.dart** function **load** in this line 
`final String name = locale.countryCode.isEmpty ? locale.languageCode : locale.toString();`

The code I'm using is this `S.load(Locale("es"));`. 

The problem is that the `Locale("es")`is returning a null value when checking for the countryCode in `locale.countryCode.isEmpty`, causing the app to crash.

**Comment by aleksakrstic** [comment]
Hi @ElZombieIsra 
Did you try with `S.load(Locale("es", ""));` for cases where you don't use country code?

In the past, passing empty string for country code was preferred due to Intl library or Material localization delegate internal implementation.

We will check if it is safe now to use Locales with null country codes as well, and try to support it with upcoming plugin updates. Especially since it is now suggested in `Locale` class documentation to pass it as null instead of empty string.

**Comment by ElZombieIsra** [comment]
Yes, I used ```Locale("es", "MX")``` and it works fine. 
I was just pointing out that it crash when it comes null. And it bugged me out that the recommended way was to pass a null value instead of an empty string. I'm using it this way right now but just for you to know.
Sorry for the late answer.

**Comment by aleksakrstic** [comment]
Good that it works fine for you as well.
No problem. It is useful for us to hear such feedbacks anyway, so we can make the plugin better.

**Comment by aleksakrstic** [comment]
Hi @ElZombieIsra 
With the new plugin version `1.4.0` you can now pass null for country code, for instance `S.load(Locale("es"));`.

**Comment by ElZombieIsra** [comment]
Thanks guys. Really appreciate it.
