### ISSUE TITLE
ARB select not working, returns Intl.message() instead.

### ISSUE THREAD

**Issue by AmruthPillai** [localizely/flutter-intl-vscode#12]
I'm trying to add a multi-option translation in my ARB, through this row:
`"categoryName": "{category, select, automobile {Automobile} babycare {Baby Care}}",`

This generates the corresponding code in messages_en.dart, which seems to be correct:
`static m0(category) => "${Intl.select(category, {'automobile': 'Automobile', 'babycare': 'Baby Care', })}";`

But when it comes to the `l10n.dart`, it loses its syntax and generates it like this:
```
String categoryName(dynamic category) {
    return Intl.message(
      '{category, select, automobile {Automobile} babycare {Baby Care}}',
      name: 'categoryName',
      desc: '',
      args: [category],
    );
  }
```

Because of this, when I try to use `S.of(context).categoryName('Automobile')` I get the entire string `{category, select, automobile {Automobile} babycare {Baby Care}}` instead of just `Automobile`.

Please help? I don't know what I can do for these type of dynamic variables.

**Comment by aleksakrstic** [comment]
Hi @AmruthPillai 

Thanks for report this with these clear instructions!

We will include a fix for this in upcoming extension releases.
Since we yet don't have clear idea about that release date, I guess the best would be if you implement some kind of a workaround for that for now. Maybe programatically, having separate keys in ARB for each case from given "select"?

**Comment by AmruthPillai** [comment]
Hey there!

That doesn't actually work either, cause there is no way to programmatically construct and access a class member dynamically during runtime. At least, I do not see any such options to do so in Dart.

Maybe one suggestion that would help? Try to add a function, something like bool hasKey(String) which would return whether a given key exists or not, or maybe some way to access the class members of S through ['key'] operator, which currently doesn't extend to classes right now, only maps.

**Comment by aleksakrstic** [comment]
Hi @AmruthPillai 

Since you will need to know what options for "select" you will have before app build time (because you will need to put them in ARB files), it will not be fully dynamic either way I guess?

If you put following string keys in ARB files:
```  
{
  ...  
  "categoryNameCar": "Automobile",
  "categoryNameBabyCare": "Baby Care"
}
```

Then you could access them in the code at least like:
```
    if (category == "babycare") {
      txt = S.of(context).categoryNameBabyCare;
    } else if (category == "automobile") {
      txt = S.of(context).categoryNameCar;
    }
```

Not the best readability due to multiple conditions, but I guess could do the work.
Is this doable in your case?

**Comment by AmruthPillai** [comment]
That's cool, thank you so much for taking the time to whip up and example snipper. Helped me understand the logic clearly. This might work. It would be a lot of code, but that's fine :) 

Thank you so much!

**Comment by aleksakrstic** [comment]
@AmruthPillai  
Custom selects are now supported with new plugin version `1.5.0`.

You can use them in "ICU select" format in ARB files like this for example:
`"pageHomeWelcomeRole": "{role, select, admin {Hi admin!} manager {Hi manager!} other {Hi visitor!}}"`

**Comment by AmruthPillai** [comment]
That's amazing, I should be updating my application soon :)
Thank you for letting me know about the update.
