### ISSUE TITLE
Respect the package context in pubspec.yaml

### ISSUE THREAD

**Issue by Wikiwix** [localizely/flutter-intl-vscode#59]
I currently use my own forks of [`intl_utils`](https://github.com/localizely/intl_utils/pull/16) and [`intl_translation`](https://github.com/dart-lang/intl_translation/pull/125) to allow it to work in my null-safe project. Using `dependency_overrides` works without issues, but the extension probably brings its own binary when it actually should just run

```bash
flutter pub run intl_utils:generate
```
which respects my setup

**Comment by lzoran** [comment]
Hi @Wikiwix,

The Flutter Intl extension uses a globally installed `intl_utils` package. 
To temp. patch the Flutter Intl extension until null-safety is supported, just globally install `intl_utils` fork on your machine.
```
flutter pub global activate --source path <PATH>
```

Hope it helps!

**Comment by Wikiwix** [comment]
This does not seem to work:

https://github.com/localizely/intl_utils/pull/16#issuecomment-754741619

**Comment by lzoran** [comment]
Hi @Wikiwix,

I believe that the problem is in the `intl_utils` version mismatch.
The Flutter Intl extension requires a specific version of the `intl_utils` package, and if it does not exist, it will install it.

For example, I'm using `Flutter Intl 1.13.0` extension in my VS Code, which depends on the `intl_utils 1.9.0`. 
The `pubspec.yaml` file of my local `intl_utils` package should have the same `version` as the one Flutter Intl extension requires.

![cmd-patch](https://user-images.githubusercontent.com/15170421/103681680-15833900-4f88-11eb-9c16-13d40bfbc148.png)

**Comment by Wikiwix** [comment]
@lzoran I tested the version mismatch of `intl_utils` on my own and it did not help, but after your comment I removed the `dependency_overwrites` and changed the version of the `intl_translation` package back to the original version. \
Now it works.

So thanks a lot! This is very valueable! Coming back to my original request: you might want to add the fact (that the extension makes use of the global `intl_util` command if the version matches) to the extension documentation
